In [4]:
import numpy as np

In [5]:
arr_0_D=np.array([1])

In [6]:
arr_0_D

array([1])

In [13]:
arr_1_D=np.array([1,2,3])

In [14]:
arr_1_D

array([1, 2, 3])

In [15]:
arr_2_D=np.array([[1,2,3],[4,5,6]])

In [16]:
arr_2_D

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr_3_D=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [18]:
arr_3_D

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [19]:
arr=np.array([1,2,3], ndmin=4)

In [20]:
arr

array([[[[1, 2, 3]]]])