In [ ]:
# practice_1.

In [10]:
import numpy as np

In [11]:
arr = np.array([1,2,3,4,5,6,7,8])

In [12]:
arr[0:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
arr[1:5]

array([2, 3, 4, 5])

In [14]:
arr[3:6]

array([4, 5, 6])

In [15]:
arr[0:7:2]

array([1, 3, 5, 7])

In [16]:
arr[-4:-2]

array([5, 6])

In [ ]:
# practice_2.

In [17]:
mt=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [18]:
mt

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
mt[0,:]

array([1, 2, 3, 4, 5])

In [20]:
mt[1,:]

array([ 6,  7,  8,  9, 10])

In [21]:
mt[0,0:3]

array([1, 2, 3])

In [22]:
mt[1,2:5]

array([ 8,  9, 10])

In [ ]:
# practice_3.

In [23]:
mtr = np.arange(10000).reshape(100,100) 

In [24]:
mtr[:,:]

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [ ]:
# practice_4.

In [25]:
mtr = np.arange(100).reshape(10,10) 

In [26]:
mtr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
mtr[0:2 , :2]

array([[ 0,  1],
       [10, 11]])

In [ ]:
mtr[2:4 , :2]

In [ ]:
mtr[4:6 , :2]

In [ ]:
mtr[6:8 , :2]

In [ ]:
mtr[8:10 , :2]

In [28]:
mtr[0:2 , 2:4]

array([[ 2,  3],
       [12, 13]])

In [ ]:
mtr[2:4 , 2:4]

In [ ]:
mtr[4:6 , 2:4]

In [ ]:
mtr[6:8 , 2:4]

In [ ]:
mtr[8:10 , 2:4]

In [29]:
mtr[0:2 , 4:6]

array([[ 4,  5],
       [14, 15]])

In [ ]:
mtr[2:4 , 4:6]

In [ ]:
mtr[4:6 , 4:6]

In [ ]:
mtr[6:8 , 4:6]

In [ ]:
mtr[8:10 , 4:6]

In [30]:
mtr[0:2 , 6:8]

array([[ 6,  7],
       [16, 17]])

In [ ]:
mtr[2:4 , 6:8]

In [ ]:
mtr[4:6 , 6:8]

In [ ]:
mtr[6:8 , 6:8]

In [ ]:
mtr[8:10 , 6:8]

In [31]:
mtr[0:2 , 8:10]

array([[ 8,  9],
       [18, 19]])

In [ ]:
mtr[2:4 , 8:10]

In [ ]:
mtr[4:6 , 8:10]

In [ ]:
mtr[6:8 , 8:10]

In [ ]:
mtr[8:10 , 8:10]